### ISSUE TITLE
Display Current Track is broken in version 9.16

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#392]
Getting exception "Invalid id"

**Comment by nikitavoloboev** [comment]
Still broken for me in 9.18

Get this in debugger

```
[12:20:15.755] Spotify Mini Player[External] Processing complete
[12:20:15.761] Spotify Mini Player[External] Passing output '' to Run Script
[12:20:17.414] Spotify Mini Player[Run Script] Processing complete
[12:20:17.417] Spotify Mini Player[Run Script] Passing output '
Notice: Undefined variable: w in /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php on line 8753

Fatal error: Uncaught Error: Call to a member function cache() on null in /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php:8631
Stack trace:
#0 /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php(8753): logMsg(NULL, 'Error(do_async_...')
#1 /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php(8801): do_async_post_request('http://api.stat...', Array)
#2 /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/action.php(77): stathat_ez_count('AlfredSpotifyMi...', 'workflow used', 1)
#3 {main}
  thrown in /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php on line 8631
' to Default Web Search
```

**Comment by vdesabou** [comment]
@nikitavoloboev I've opened #398 to track this issue. It can happen if you've blocked access to stathat (I'm using it to send anonymous metrics). But I don't see how it can impact Display Current Track 
I'll post a beta version in #398, let me know if that fixes this issue

**Comment by nikitavoloboev** [comment]
beta fixed the current track issue but searching for anything still returns no results

**Comment by piersolenski** [comment]
Also having this issue with 9.11
