### ISSUE TITLE
Uncaught Error when updating stathat metrics

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#398]
```
Notice: Undefined variable: w in /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php on line 8753

Fatal error: Uncaught Error: Call to a member function cache() on null in /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php:8631
Stack trace:
#0 /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php(8753): logMsg(NULL, 'Error(do_async_...')
#1 /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php(8801): do_async_post_request('http://api.stat...', Array)
#2 /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/action.php(77): stathat_ez_count('AlfredSpotifyMi...', 'workflow used', 1)
#3 {main}
  thrown in /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6A25411A-2627-4B4A-8DFA-7B491E56A919/src/functions.php on line 8631
' to Default Web Search
```

**Comment by vdesabou** [comment]
@nikitavoloboev Can you try this beta please https://transfer.sh/hRUDR/spotifyminiplayer-beta.alfredworkflow
